services:
  backend:
    build: './backend'
    ports:
      - "8005:8005"

  frontend:
    build: './frontend'
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - "./frontend/.env.prod"  